### PR TITLE
[chart] Create a service monitor for each script

### PR DESCRIPTION
**Pull request by BapRx**
Hi, this PR allows us to track the scripts using a service monitor instead of [manually configuring](https://github.com/ricoberger/script_exporter?tab=readme-ov-file#prometheus-configuration) the prometheus additional scrape configs. 

If you prefer adding a separate option under `.Values.serviceMonitor` to enable those extra resources I can edit this PR.

I also bumped the image tag to `v2.17.0` in the `appVersion`.

### CODE REVIEW

**Comment by ricoberger** [comment]
Hi @BapRx thanks for your contribution 🙂

> If you prefer adding a separate option under .Values.serviceMonitor to enable those extra resources I can edit this PR.

I think a separate option would make sense. Can you please add it?

**Comment by BapRx** [comment]
Another option while we're still implementing this would be to handle this like [prometheus-blackbox-exporter](https://github.com/prometheus-community/helm-charts/blob/cd640243eb03787fab11cf2883534f604787f760/charts/prometheus-blackbox-exporter/values.yaml#L265-L309) does, it's not automatically creating a serviceMonitor for each target but allows the user to enable or disable it per probe. The selfMonitor is also optional and disabled by default (we could set it to true to avoid a breaking change).

What method do you prefer?

**Comment by ricoberger** [comment]
Hi, the implementation from the blackbox exporter Helm chart looks awesome and providing the same functionality would be great.

But I'm also fine with creating a default ServiceMonitor per probe in a first step, because this is already a huge improvement.

**Comment by BapRx** [comment]
I just pushed a new commit which brings the best of both worlds (I hope!), it defaults to the automatic discovery but also allows the users to override this behavior by providing a list of the scripts to scrape.

I enabled the self-serviceMonitor by default.

**Comment by ricoberger** [comment]
Awesome @BapRx, thanks again 🙂

**Pull request merged**
