### PR TITLE
windows version

### PR DESCRIPTION
**Pull request by skpenpen**
windows version 
+flag to disable args

### CODE REVIEW

**Comment by ricoberger** [comment]
Hi @skpenpen thanks for your contribution 🙂

Would it be possible to check the OS in the main function, instead of haven the main file duplicated for unix based systems and windows:

```go
if runtime.GOOS == "windows" {
    // Windows logic
} else {
    // Unix logic
}
```

**Comment by skpenpen** [comment]
No its not possible due to import problem.
You would have Windows imports in the same file than Unix, and it wont compile for Unix.
For what i know and tried...

**Comment by ricoberger** [comment]
Ok, thanks for your feedback.

I'm still not sure about the duplicated code. What do you think about moving the `cmd/script_exporter/script_exporter.go` file to a package named `exporter` or sth. similar and exporting the `main` function as sth. like `Run`. Then we can have a `cmd/windows` and `cmd/unix` package which just calls the exported `Run` function from the `exporter` package?

**Comment by skpenpen** [comment]
> Ok, thanks for your feedback.
> 
> I'm still not sure about the duplicated code. What do you think about moving the `cmd/script_exporter/script_exporter.go` file to a package named `exporter` or sth. similar and exporting the `main` function as sth. like `Run`. Then we can have a `cmd/windows` and `cmd/unix` package which just calls the exported `Run` function from the `exporter` package?

Done

**Comment by ricoberger** [comment]
Awesome work @skpenpen, thank you very much.

**Pull request merged**
